export const skillDefinitions = [
  {
    id: 'requirements-authoring',
    workflow: 'requirements',
    title: 'Requirements Authoring',
    description: 'Creates structured requirements.yaml artifacts with traceable FR/NFR/AC IDs.',
    overview: 'This skill drives the requirements stage. The CLI owns step detection, artifact status, validation, and finalization.',
    steps: [
      { name: 'needs_input', text: 'Choose an existing change directory or provide a new request.' },
      { name: 'init', text: 'Initialize the requirements artifact and read relevant living docs.' },
      { name: 'discovery', text: 'Ask one question at a time and record answers until the discovery gate passes.' },
      { name: 'assumptions', text: 'List and classify assumptions. Mark the step complete only if none remain.' },
      { name: 'drafting', text: 'Draft FRs, NFRs, and ACs. Use data.next_ids for new IDs.' },
      { name: 'validation', text: 'Fix mechanical findings. The CLI will inject semantic checks to review.' },
      { name: 'delta', text: 'Add docs/current delta entries for affected living docs.' },
      { name: 'recovery', text: 'If rejected, fix findings from the review file and finalize again.' },
      { name: 'ready', text: 'All gates passed. Finalize the artifact.' },
      { name: 'complete', text: 'The artifact is ready for review.' },
    ],
    commands: [
      'node "$SDLC_CLI" requirements --dir <change-dir>',
      'node "$SDLC_CLI" requirements --request "<request text>"',
      'node "$SDLC_CLI" requirements --dir <change-dir> --next-ids',
      'node "$SDLC_CLI" requirements --dir <change-dir> --record-answer --lens <lens> --question "<question>" --answer "<answer>"',
      'node "$SDLC_CLI" requirements --dir <change-dir> --set-clarity <clear|partial|vague>',
      'node "$SDLC_CLI" requirements --dir <change-dir> --update-artifact < requirements.yaml',
      'node "$SDLC_CLI" requirements --dir <change-dir> --append-delta < delta.yaml',
      'node "$SDLC_CLI" requirements --dir <change-dir> --complete-step --step assumptions',
      'node "$SDLC_CLI" requirements --dir <change-dir> --finalize',
      'node "$SDLC_CLI" requirements --dir <change-dir> --finalize --confirm-semantic',
    ],
  },
  {
    id: 'design-authoring',
    workflow: 'design',
    title: 'Design Authoring',
    description: 'Creates structured design.yaml artifacts from requirements.yaml.',
    overview: 'This skill drives the design stage. It produces components, data models, APIs, decisions, and traceability.',
    steps: [
      { name: 'needs_input', text: 'Choose the change directory to design.' },
      { name: 'init', text: 'Initialize design.yaml and pin it to requirements.yaml version.' },
      { name: 'drafting', text: 'Draft components, data models, APIs, decisions, and traceability.' },
      { name: 'validation', text: 'Fix mechanical findings. The CLI will inject semantic checks to review.' },
      { name: 'delta', text: 'Add docs/current delta entries for affected living docs.' },
      { name: 'recovery', text: 'If rejected, fix findings from design-review.yaml and finalize again.' },
      { name: 'ready', text: 'All gates passed. Finalize the artifact.' },
      { name: 'complete', text: 'The design artifact is ready for review.' },
    ],
    commands: [
      'node "$SDLC_CLI" design --dir <change-dir>',
      'node "$SDLC_CLI" design --dir <change-dir> --next-ids',
      'node "$SDLC_CLI" design --dir <change-dir> --update-artifact < design.yaml',
      'node "$SDLC_CLI" design --dir <change-dir> --append-delta < delta.yaml',
      'node "$SDLC_CLI" design --dir <change-dir> --finalize',
      'node "$SDLC_CLI" design --dir <change-dir> --finalize --confirm-semantic',
    ],
  },
  {
    id: 'planning',
    workflow: 'planning',
    title: 'Planning',
    description: 'Creates structured plan.yaml artifacts from design.yaml and requirements.yaml.',
    overview: 'This skill drives the planning stage. It produces tasks, dependencies, requirement coverage, and file operation intent.',
    steps: [
      { name: 'needs_input', text: 'Choose the change directory to plan.' },
      { name: 'init', text: 'Initialize plan.yaml and pin it to design.yaml and requirements.yaml versions.' },
      { name: 'drafting', text: 'Draft tasks with covers, acceptance_ids, depends_on, files, and status.' },
      { name: 'validation', text: 'Fix mechanical findings. The CLI will inject semantic checks to review.' },
      { name: 'delta', text: 'Add docs/current delta entries for affected living docs.' },
      { name: 'recovery', text: 'If rejected, fix findings from plan-review.yaml and finalize again.' },
      { name: 'ready', text: 'All gates passed. Finalize the artifact.' },
      { name: 'complete', text: 'The plan artifact is ready for review.' },
    ],
    commands: [
      'node "$SDLC_CLI" planning --dir <change-dir>',
      'node "$SDLC_CLI" planning --dir <change-dir> --next-ids',
      'node "$SDLC_CLI" planning --dir <change-dir> --update-artifact < plan.yaml',
      'node "$SDLC_CLI" planning --dir <change-dir> --append-delta < delta.yaml',
      'node "$SDLC_CLI" planning --dir <change-dir> --finalize',
      'node "$SDLC_CLI" planning --dir <change-dir> --finalize --confirm-semantic',
    ],
  },
  {
    id: 'implementation',
    workflow: 'implementation',
    title: 'Implementation',
    description: 'Updates task execution state in plan.yaml during implementation.',
    overview: 'This skill updates task status, notes, and changed files inside plan.yaml.',
    steps: [
      { name: 'progress', text: 'Show implementation progress from plan.yaml task state.' },
      { name: 'task_update', text: 'Update a task status, note, and files_changed.' },
      { name: 'ready', text: 'When all tasks are done or skipped, run implementation review.' },
    ],
    commands: [
      'node "$SDLC_CLI" implementation --dir <change-dir>',
      'node "$SDLC_CLI" implementation --dir <change-dir> --task-id TASK-001 --status in_progress --note "Started work"',
      'node "$SDLC_CLI" implementation --dir <change-dir> --task-id TASK-001 --status done --note "Implemented" --files "create:src/a.ts,modify:src/b.ts"',
      'node "$SDLC_CLI" review --target implementation --dir <change-dir> --accept',
    ],
  },
  {
    id: 'review',
    workflow: 'review',
    title: 'Review Gate',
    description: 'Reviews requirements.yaml, design.yaml, plan.yaml, or implementation state.',
    overview: 'This skill runs the review gate. It writes artifact-specific review files with review rounds and accepts or rejects the reviewed target.',
    steps: [
      { name: 'review', text: 'Run mechanical and semantic review against the target artifact.' },
    ],
    commands: [
      'node "$SDLC_CLI" review --target requirements --dir <change-dir> --accept',
      'node "$SDLC_CLI" review --target design --dir <change-dir> --accept',
      'node "$SDLC_CLI" review --target plan --dir <change-dir> --accept',
      'node "$SDLC_CLI" review --target implementation --dir <change-dir> --accept',
      'node "$SDLC_CLI" review --target requirements --dir <change-dir> --reject',
    ],
  },
  {
    id: 'feedback',
    workflow: 'feedback',
    title: 'Cross-Stage Feedback',
    description: 'Pauses the current stage and reverts a previous stage to draft for corrections.',
    overview: 'Use this skill when you find a flaw in an already-accepted previous stage (e.g., Design finds a flaw in Requirements).',
    steps: [
      { name: 'create', text: 'Revert the target stage to draft and block the current stage.' },
      { name: 'resolve', text: 'After fixing the target stage and re-reviewing it, resolve the feedback to unblock the current stage.' },
    ],
    commands: [
      'node "$SDLC_CLI" feedback --dir <change-dir> --from <current-stage> --to <previous-stage> --reason "..."',
      'node "$SDLC_CLI" feedback --dir <change-dir> --resolve <FB-id>',
    ],
  },
  {
    id: 'knowledge-extraction',
    workflow: 'knowledge-extraction',
    title: 'Knowledge Extraction',
    description: 'Synchronizes docs/current from approved changes using deltas.',
    overview: 'This skill lists the deltas to apply to docs/current. After updating the docs, mark extraction as complete.',
    steps: [
      { name: 'docs_delta', text: 'Read the deltas to apply from the CLI output.' },
      { name: 'updating_docs', text: 'Manually edit docs/current files to apply the deltas.' },
      { name: 'complete', text: 'Run the complete command to mark knowledge extraction as done.' },
    ],
    commands: [
      'node "$SDLC_CLI" knowledge-extraction --dir <change-dir>',
      'node "$SDLC_CLI" knowledge-extraction --dir <change-dir> --complete',
    ],
  },
];