/**
 * index provider: renders docs/current/index.md as a whole-file generator.
 * The nine document rows are contract data declared here (DEC-003/DEC-004);
 * the Cross-Check table is computed against the rendered docs and the repo
 * in the same run; the Notes table carries the dead-reference scan. Any
 * cross-check violation aborts generation — the fast gate must not pass
 * with an inconsistent living-doc set.
 *
 * Manifest ordering contract: this provider must run after the
 * architecture, dependencies, known-issues, and glossary entries —
 * cross-checks read those files' in-flight rendered content.
 */

import fs from 'node:fs';
import path from 'node:path';

import { findImportSites, scanDeadReferences } from '../scans.ts';
import { renderTable, tableRowsUnderHeading } from '../table.ts';
import type { FileProvider, ProviderContext } from '../types.ts';

const REL_PATH = 'docs/current/index.md';

/** Contract-frozen document table (DEC-003/DEC-004): four columns, nine rows. */
const DOC_TABLE_HEADERS = ['File', 'Purpose', 'When to Read', 'Notes'];
const DOC_TABLE: string[][] = [
  ['architecture.md', 'Tech stack, boundaries, folder responsibilities', 'Structural changes', 'docs-gen regions; judgment prose by knowledge extraction'],
  ['api-contract.md', 'Endpoints: method, path, auth, shapes', 'API changes', 'docs-gen regions; judgment prose by knowledge extraction'],
  ['glossary.md', 'Entities, fields, relationships, rules', 'Data layer changes', 'docs-gen regions; judgment prose by knowledge extraction'],
  ['capabilities.md', 'Features, workflows, user journeys', 'Feature changes', 'Maintained by knowledge extraction'],
  ['conventions.md', 'Patterns, naming, error handling, file org', 'Code writing', 'docs-gen region (checks reference); judgment by knowledge extraction'],
  ['operations.md', 'Build, test, lint, deploy, env vars', 'Verification', 'docs-gen regions; baselines by knowledge extraction'],
  ['dependencies.md', 'Key libraries and roles', 'Dependency changes', 'Generated by docs-gen (docs:check enforced)'],
  ['known-issues.md', 'Markers, skipped tests', 'Task estimation', 'Generated by docs-gen; review-justified section curated'],
  ['decisions.md', 'Cycle decisions rendered from accepted change artifacts', 'Architectural changes', 'Generated by docs-gen (merge-by-key)'],
];

/** Declared entity → command-surface mapping (check 1 and check 2). */
const ENTITY_COMMANDS: Record<string, string[]> = {
  'Stage Descriptor (stage.yaml)': [
    'sdlc <stage-id>',
    'sdlc requirements',
    'sdlc design',
    'sdlc planning',
    'sdlc implementation',
  ],
  'CLI Envelope': ['sdlc --list-workflows', 'sdlc status', 'sdlc feedback', 'sdlc doctor'],
  'Artifact Status': ['sdlc feedback', 'sdlc <review-stage>'],
  'Review Round (review file rounds[])': [
    'sdlc <review-stage>',
    'sdlc requirements-review',
    'sdlc design-review',
    'sdlc planning-review',
    'sdlc implementation-review',
  ],
  'Docs Delta (docs-delta.yaml)': ['sdlc knowledge-extraction'],
  'Plan Task (plan.yaml)': ['sdlc implementation'],
  'Skill Folder (src/skills)': ['npm run deploy:smoke'],
  'Agent Definition (src/agents/<agent-id>.yaml)': [
    'sdlc <stage-id>',
    'node bin/deploy-to-agent.ts',
  ],
  'Kind Permission Contract': ['node bin/deploy-to-agent.ts'],
  'Platform Renderer': ['node bin/deploy-to-agent.ts'],
  'Agent Audit (src/skills/agent-audit/SKILL.md)': ['agent skill (not a CLI command)'],
  'Model Override': ['sdlc <stage-id>', 'node bin/deploy-to-agent.ts'],
  'Improvement Review (src/skills/improvement-review)': ['agent skill (not a CLI command)'],
  'Idea Document (docs/ideas/<slug>.md)': ['agent skill (not a CLI command)'],
};

/** Technologies decisions may cite; each must appear in the tech stack. */
const TECH_VOCABULARY = ['YAML', 'Node.js', 'tsup', 'ajv', 'TypeScript'];

const CROSS_CUTTING = ['status', 'feedback', 'doctor'];

export const indexProvider: FileProvider = {
  mode: 'file',
  render(ctx: ProviderContext): string[] {
    const violations: string[] = [];

    const glossary = ctx.readExisting('docs/current/glossary.md');
    const architecture = ctx.readExisting('docs/current/architecture.md');
    const capabilities = ctx.readExisting('docs/current/capabilities.md');
    const dependencies = ctx.readExisting('docs/current/dependencies.md');
    const knownIssues = ctx.readExisting('docs/current/known-issues.md');
    const decisions = ctx.readExisting('docs/current/decisions.md');

    const stageIds = stageIdsFromRegistry(ctx.root);
    const npmScripts = npmScriptNames(ctx.root);
    const bins = binFiles(ctx.root);

    // Check 1: every glossary entity declares a mapping; concrete targets exist.
    const entities = entityHeadings(glossary);
    for (const entity of entities) {
      const mapped = ENTITY_COMMANDS[entity];
      if (!mapped || mapped.length === 0) {
        violations.push(`glossary entity '${entity}' maps to no CLI command or bin`);
        continue;
      }
      for (const token of mapped) {
        if (!mappedTargetExists(token, stageIds, npmScripts, bins)) {
          violations.push(`entity '${entity}' maps to unknown command '${token}'`);
        }
      }
    }

    // Check 2: every stage and cross-cutting command is covered by an entity.
    const mappedText = JSON.stringify(ENTITY_COMMANDS);
    for (const id of [...stageIds, ...CROSS_CUTTING]) {
      if (!mappedText.includes(id)) {
        violations.push(`command '${id}' maps to no glossary entity`);
      }
    }

    // Check 3: every architecture folder appears in at least one other doc.
    const otherDocs = [dependencies, knownIssues, glossary, capabilities, decisions]
      .concat([ctx.readExisting('docs/current/api-contract.md'), ctx.readExisting('docs/current/operations.md'), ctx.readExisting('docs/current/conventions.md')]);
    for (const folder of architectureFolders(architecture)) {
      const covered = otherDocs.some((doc) => doc.includes(folder));
      if (!covered) violations.push(`architecture folder '${folder}' appears in no other doc`);
    }

    // Check 4: scan-found known-issue locations live under architecture folders.
    const folders = architectureFolders(architecture);
    for (const location of tableRowsUnderHeading(knownIssues, 'Markers').map((row) => row[0] ?? '')) {
      const clean = location.replace(/\s*\(.*\)\s*$/, '');
      if (clean && !folders.some((folder) => clean.startsWith(folder))) {
        violations.push(`known-issue location '${location}' is not under an architecture folder`);
      }
    }

    // Check 5: every capability row cites a related entity or endpoint.
    for (const row of tableRowsUnderHeading(capabilities, 'Capabilities')) {
      const relatedEntities = (row[2] ?? '').trim();
      const relatedEndpoints = (row[3] ?? '').trim();
      if (isPlaceholder(relatedEntities) && isPlaceholder(relatedEndpoints)) {
        violations.push(`capability '${row[0] ?? '?'}' cites no related entity or endpoint`);
      }
    }

    // Check 6: every runtime dependency is imported somewhere.
    for (const row of tableRowsUnderHeading(dependencies, 'Key Dependencies')) {
      const name = row[0] ?? '';
      if (!name) continue;
      const imported =
        findImportSites(ctx.root, name).length > 0 ||
        findImportSites(ctx.root, name, ['generate_context.js']).length > 0;
      if (!imported) {
        violations.push(`dependency '${name}' is never imported in source`);
      }
    }

    // Check 7: every declared decision technology is in the tech stack.
    const techStack = techStackTechnologies(architecture);
    for (const tech of TECH_VOCABULARY) {
      if (!techStack.some((entry) => entry.toLowerCase().includes(tech.toLowerCase()))) {
        violations.push(`decision technology '${tech}' is missing from the tech stack`);
      }
    }

    if (violations.length > 0) {
      throw new Error(
        `docs-gen: cross-check violations (${violations.length}):\n - ${violations.join('\n - ')}`
      );
    }

    const staleRefs = scanDeadReferences(ctx.root);
    const notesSection =
      staleRefs.length > 0
        ? renderTable(
            ['Note', 'Location', 'Detail'],
            staleRefs.map((hit) => ['STALE-REF', hit.file, `${hit.section}: references missing ${hit.reference}`])
          )
        : renderTable(['Note', 'Location', 'Detail'], [['none', '—', '—']]);

    const results: string[][] = [
      ['1', 'Glossary entity with no API endpoint', 'None — each entity maps to a CLI command or bin'],
      ['2', 'API endpoint with no glossary entity', 'None — commands map to Envelope, Stage Descriptor, Skill Folder, Docs Delta, Plan Task'],
      ['3', 'Architecture module not in any other doc', 'None — every folder in architecture.md appears in at least one other doc'],
      ['4', 'Known-issue location not in architecture folders', 'None'],
      ['5', 'Capability with no related endpoint or entity', 'None'],
      ['6', 'Dependency never imported in source', 'None'],
      ['7', 'Decision referencing a technology not in tech stack', 'None'],
    ];

    return [
      '# /docs/current/ — Knowledge Index',
      '',
      ...renderTable(DOC_TABLE_HEADERS, DOC_TABLE),
      '',
      '## Cross-Check',
      '',
      ...renderTable(['#', 'Check', 'Result'], results),
      '',
      ...notesSection,
      '',
    ];
  },
};

function isPlaceholder(value: string): boolean {
  const trimmed = value.trim();
  return trimmed.length === 0 || trimmed === '—' || trimmed === '-';
}

/** Validates one declared mapping token against the live command surface. */
function mappedTargetExists(
  token: string,
  stageIds: string[],
  npmScripts: Set<string>,
  bins: Set<string>
): boolean {
  const trimmed = token.trim();
  if (trimmed === 'agent skill (not a CLI command)') return true;
  if (trimmed.includes('<')) return true; // pattern reference (sdlc <stage-id>)
  const sdlcMatch = trimmed.match(/^sdlc ([\w-]+)$/);
  if (sdlcMatch) {
    return (
      sdlcMatch[1].startsWith('--') ||
      stageIds.includes(sdlcMatch[1]) ||
      CROSS_CUTTING.includes(sdlcMatch[1])
    );
  }
  const npmMatch = trimmed.match(/^npm run ([\w:.-]+)$/);
  if (npmMatch) return npmScripts.has(npmMatch[1]);
  const binMatch = trimmed.match(/^node (bin\/[\w.-]+\.ts)$/);
  if (binMatch) return bins.has(binMatch[1]);
  return stageIds.includes(trimmed) || CROSS_CUTTING.includes(trimmed);
}

function npmScriptNames(root: string): Set<string> {
  const raw = fs.readFileSync(path.join(root, 'package.json'), 'utf8');
  const pkg = JSON.parse(raw) as { scripts?: Record<string, string> };
  return new Set(Object.keys(pkg.scripts ?? {}));
}

function binFiles(root: string): Set<string> {
  const binDir = path.join(root, 'bin');
  if (!fs.existsSync(binDir)) return new Set();
  return new Set(
    fs.readdirSync(binDir).filter((name) => name.endsWith('.ts')).map((name) => `bin/${name}`)
  );
}

function stageIdsFromRegistry(root: string): string[] {
  const stagesDir = path.join(root, 'src', 'stages');
  if (!fs.existsSync(stagesDir)) return [];
  return fs
    .readdirSync(stagesDir)
    .filter((name) => fs.statSync(path.join(stagesDir, name)).isDirectory())
    .sort();
}

function entityHeadings(glossary: string): string[] {
  const out: string[] = [];
  for (const line of glossary.split('\n')) {
    const match = line.match(/^## Entity: (.+?)\s*$/);
    if (match) out.push(match[1]);
  }
  return out;
}

function architectureFolders(architecture: string): string[] {
  return tableRowsUnderHeading(architecture, 'Folder Responsibilities')
    .map((row) => row[0] ?? '')
    .filter((folder) => folder.endsWith('/'));
}

function techStackTechnologies(architecture: string): string[] {
  return tableRowsUnderHeading(architecture, 'Tech Stack').map((row) => row[1] ?? '');
}

export { REL_PATH as INDEX_REL_PATH };
